import { postalCodes } from "@openng/db";
import type { ResourceConfig } from "../../resource-factory/resource-config";

export const postalCodesConfig: ResourceConfig = {
  name: "postal-codes",
  table: postalCodes,
  description:
    "Nigerian postal code assignments by state, LGA, and area, consolidated from NIPOST with corroborated community coverage.",
  version: "1",
  updateFrequency: "static",
  source: "NIPOST postcode finder with corroboration from community directories",
  sourceUrl: "https://nipost.gov.ng/postcode-finder/",
  defaultSort: "stateSlug",
  defaultSortOrder: "asc",
  maxPageSize: 200,
  filters: [
    { param: "state", column: "stateSlug", type: "in" },
    { param: "lga", column: "lgaSlug", type: "in" },
    { param: "postal_code", column: "postalCode", type: "exact" },
    { param: "area", column: "areaName", type: "ilike" },
    { param: "is_verified", column: "isVerified", type: "exact", coerce: "boolean" },
    { param: "confidence", column: "confidence", type: "in" },
  ],
  selectColumns: [
    "id",
    "stateSlug",
    "lgaSlug",
    "areaName",
    "postOfficeName",
    "postalCode",
    "regionDigit",
    "isVerified",
    "confidence",
    "sourceKind",
    "sourceUrl",
    "sourceDate",
    "createdAt",
    "updatedAt",
  ],
  fields: [
    { name: "stateSlug", type: "string" },
    { name: "lgaSlug", type: "string" },
    { name: "areaName", type: "string" },
    { name: "postOfficeName", type: "string" },
    { name: "postalCode", type: "string" },
    { name: "regionDigit", type: "integer" },
    { name: "isVerified", type: "boolean" },
    { name: "confidence", type: "string", display: "badge" },
    { name: "sourceKind", type: "string", display: "badge" },
    { name: "sourceUrl", type: "string" },
    { name: "sourceDate", type: "date", format: "YYYY-MM-DD" },
  ],
  indexes: [
    { columns: ["state_slug"], type: "btree" },
    { columns: ["state_id", "lga_id"], type: "btree" },
    { columns: ["state_slug", "area_name"], type: "btree" },
    { columns: ["postal_code"], type: "btree" },
    { columns: ["state_id", "lga_id", "area_name", "postal_code"], type: "btree", unique: true },
  ],
  docsUrl: "https://docs.openng.dev",
};
