/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as dashboardUsageRouteImport } from './routes/(dashboard)/usage'
import { Route as dashboardSettingsRouteImport } from './routes/(dashboard)/settings'
import { Route as dashboardKeysRouteImport } from './routes/(dashboard)/keys'
import { Route as dashboardResourceIdRouteImport } from './routes/(dashboard)/$resourceId'
import { Route as dashboardOverviewIndexRouteImport } from './routes/(dashboard)/overview/index'
import { Route as dashboardExploreIndexRouteImport } from './routes/(dashboard)/explore/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardUsageRoute = dashboardUsageRouteImport.update({
  id: '/(dashboard)/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardSettingsRoute = dashboardSettingsRouteImport.update({
  id: '/(dashboard)/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardKeysRoute = dashboardKeysRouteImport.update({
  id: '/(dashboard)/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardResourceIdRoute = dashboardResourceIdRouteImport.update({
  id: '/(dashboard)/$resourceId',
  path: '/$resourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardOverviewIndexRoute = dashboardOverviewIndexRouteImport.update({
  id: '/(dashboard)/overview/',
  path: '/overview/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardExploreIndexRoute = dashboardExploreIndexRouteImport.update({
  id: '/(dashboard)/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$resourceId': typeof dashboardResourceIdRoute
  '/keys': typeof dashboardKeysRoute
  '/settings': typeof dashboardSettingsRoute
  '/usage': typeof dashboardUsageRoute
  '/explore/': typeof dashboardExploreIndexRoute
  '/overview/': typeof dashboardOverviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$resourceId': typeof dashboardResourceIdRoute
  '/keys': typeof dashboardKeysRoute
  '/settings': typeof dashboardSettingsRoute
  '/usage': typeof dashboardUsageRoute
  '/explore': typeof dashboardExploreIndexRoute
  '/overview': typeof dashboardOverviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(dashboard)/$resourceId': typeof dashboardResourceIdRoute
  '/(dashboard)/keys': typeof dashboardKeysRoute
  '/(dashboard)/settings': typeof dashboardSettingsRoute
  '/(dashboard)/usage': typeof dashboardUsageRoute
  '/(dashboard)/explore/': typeof dashboardExploreIndexRoute
  '/(dashboard)/overview/': typeof dashboardOverviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$resourceId'
    | '/keys'
    | '/settings'
    | '/usage'
    | '/explore/'
    | '/overview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$resourceId'
    | '/keys'
    | '/settings'
    | '/usage'
    | '/explore'
    | '/overview'
  id:
    | '__root__'
    | '/'
    | '/(dashboard)/$resourceId'
    | '/(dashboard)/keys'
    | '/(dashboard)/settings'
    | '/(dashboard)/usage'
    | '/(dashboard)/explore/'
    | '/(dashboard)/overview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  dashboardResourceIdRoute: typeof dashboardResourceIdRoute
  dashboardKeysRoute: typeof dashboardKeysRoute
  dashboardSettingsRoute: typeof dashboardSettingsRoute
  dashboardUsageRoute: typeof dashboardUsageRoute
  dashboardExploreIndexRoute: typeof dashboardExploreIndexRoute
  dashboardOverviewIndexRoute: typeof dashboardOverviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/usage': {
      id: '/(dashboard)/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof dashboardUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/settings': {
      id: '/(dashboard)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof dashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/keys': {
      id: '/(dashboard)/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof dashboardKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/$resourceId': {
      id: '/(dashboard)/$resourceId'
      path: '/$resourceId'
      fullPath: '/$resourceId'
      preLoaderRoute: typeof dashboardResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/overview/': {
      id: '/(dashboard)/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof dashboardOverviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/explore/': {
      id: '/(dashboard)/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof dashboardExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  dashboardResourceIdRoute: dashboardResourceIdRoute,
  dashboardKeysRoute: dashboardKeysRoute,
  dashboardSettingsRoute: dashboardSettingsRoute,
  dashboardUsageRoute: dashboardUsageRoute,
  dashboardExploreIndexRoute: dashboardExploreIndexRoute,
  dashboardOverviewIndexRoute: dashboardOverviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
