export enum ErrorCode {
  NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
  INVALID_FILTER = "INVALID_FILTER",
  INVALID_PARAM = "INVALID_PARAM",
  NOT_FOUND = "NOT_FOUND",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  CONFLICT = "CONFLICT",
}
