import { holidays } from "@openng/db";
import type { ResourceConfig } from "../../resource-factory/resource-config";

export const holidaysConfig: ResourceConfig = {
  name: "holidays",
  table: holidays,
  description: "Federal public holidays in Nigeria (fixed, moveable Christian, moveable Islamic, and declared special days).",
  version: "1",
  updateFrequency: "yearly",
  source: "Federal Government of Nigeria (Public Holidays Act and annual Ministry of Interior notices)",
  sourceUrl: "https://openng.dev",
  defaultSort: "date",
  defaultSortOrder: "asc",
  maxPageSize: 100,
  filters: [
    { param: "year", column: "year", type: "in", coerce: "integer" },
    { param: "category", column: "category", type: "in" },
    { param: "schedule_kind", column: "scheduleKind", type: "in" },
    { param: "is_confirmed", column: "isConfirmed", type: "exact", coerce: "boolean" },
    { param: "name", column: "name", type: "ilike" },
    { param: "date_from", column: "date", type: "range_gte" },
    { param: "date_to", column: "date", type: "range_lte" },
  ],
  selectColumns: [
    "id",
    "name",
    "date",
    "dayOfWeek",
    "category",
    "scheduleKind",
    "year",
    "isConfirmed",
    "observanceNote",
    "sourceUrl",
    "sourceDate",
    "createdAt",
    "updatedAt",
  ],
  fields: [
    { name: "name", type: "string" },
    { name: "date", type: "date", format: "YYYY-MM-DD" },
    { name: "dayOfWeek", type: "string" },
    { name: "category", type: "string", display: "badge" },
    { name: "scheduleKind", type: "string", display: "badge" },
    { name: "year", type: "integer" },
    { name: "isConfirmed", type: "boolean" },
    { name: "observanceNote", type: "string" },
    { name: "sourceUrl", type: "string" },
    { name: "sourceDate", type: "date", format: "YYYY-MM-DD" },
  ],
  indexes: [
    { columns: ["year"], type: "btree" },
    { columns: ["date"], type: "btree" },
    { columns: ["category"], type: "btree" },
    { columns: ["schedule_kind"], type: "btree" },
    { columns: ["is_confirmed"], type: "btree" },
    { columns: ["name", "date"], type: "btree", unique: true },
  ],
  docsUrl: "https://docs.openng.dev",
};
